import {z} from 'zod';
import {actor,body,reply,fail,sql,actorGuard,audit,rate,AccessError,now} from '@/lib/access/server';
import {database,categoryTree} from '@/lib/store-data';
import {subcategories,colors,packOptions} from '@/lib/listing-options';
import {ORIGIN} from '@/lib/access/policy';
const mediaUrl=z.string().refine(v=>{try{const url=new URL(v);return (v.startsWith(ORIGIN+'/api/media/')||((url.hostname==='localhost'||url.hostname==='127.0.0.1')&&url.pathname.startsWith('/api/media/')))&&/^[a-f0-9-]{36}$/.test(url.pathname.split('/').pop()||'')}catch{return false}},{message:'Upload a product image before saving.'});
const information=z.object({category:z.string().min(1,'Choose a category.'),subcategory:z.string().min(1,'Choose a subcategory.'),sku:z.string().trim().min(2,'Enter a SKU name.').max(60).regex(/^[a-zA-Z0-9 _-]+$/,'SKU can use letters, numbers, spaces, underscores and hyphens.'),variants:z.array(z.object({color:z.string().refine(c=>colors.includes(c),{message:'Choose a color, or select Not applicable.'}),option:z.string().refine(v=>packOptions.includes(v),{message:'Choose an option.'}),image:mediaUrl})).min(1).max(8)}).refine(d=>new Set(d.variants.map(v=>v.color+'|'+v.option)).size===d.variants.length,{message:'Each color and option combination must be unique.'});
function validationMessages(error:z.ZodError){
 const labels:Record<string,string>={category:'Category',subcategory:'Subcategory',sku:'SKU name',variants:'Product variant',color:'Color',option:'Option',image:'Image',name:'Product name',description:'Description',features:'Features',price:'Price',old:'Compare-at price',offerPrice:'Offer price',offerStart:'Offer start date',offerEnd:'Offer end date',status:'Visibility'};
 const messages=error.issues.map(issue=>{
  const path=issue.path.map(part=>typeof part==='number'?`#${part+1}`:labels[String(part)]||String(part)).join(' ');
  return path?`${path}: ${issue.message}`:issue.message;
 });
 return Array.from(new Set(messages));
}
export async function GET(req:Request){try{await actor('content.edit');const id=new URL(req.url).searchParams.get('id');if(!id){const rows=await sql("SELECT id,data,created_at FROM listing_drafts WHERE state='draft' ORDER BY created_at DESC LIMIT 20").all<any>();return reply({rows:rows.results.map(r=>({id:r.id,sku:JSON.parse(r.data).sku,createdAt:r.created_at}))});}const row=await sql('SELECT * FROM listing_drafts WHERE id=?',id||'').first<any>();if(!row)throw new AccessError(404,'Draft not found.');return reply({...row,data:JSON.parse(row.data)});}catch(e){return fail(e)}}
export async function POST(req:Request){try{const d=await body(req),u=await actor('content.edit');await rate(u.id,'listing-save',40);
 if(d.action==='draft'){const data=information.parse(d.data);const tree=await categoryTree();const parent=tree.find(node=>node.enabled&&node.name===data.category);const validSubcategories=parent?.children?.filter(node=>node.enabled).map(node=>node.name)||subcategories[data.category]||[];if(!((parent||subcategories[data.category])&&validSubcategories.includes(data.subcategory)))throw new AccessError(400,'Choose an active category and subcategory.');const id=crypto.randomUUID();await database().batch([...actorGuard(u),sql('INSERT INTO listing_drafts (id,data,state,created_by,created_at) VALUES (?,?,\'draft\',?,?)',id,JSON.stringify(data),u.id,now()),await audit(u,'content.listing_draft',id,'Saved product information and images')]);return reply({id},201);}
 const input=z.object({action:z.literal('finish'),id:z.string().uuid(),name:z.string().trim().min(3).max(75),description:z.string().trim().min(10).max(3000),features:z.array(z.string().trim().min(1).max(180)).max(8),price:z.number().int().min(1).max(10000000),old:z.number().int().min(1).max(10000000),offerPrice:z.number().int().min(0).max(10000000).optional(),offerStart:z.string().max(20).optional(),offerEnd:z.string().max(20).optional(),status:z.enum(['Draft','Active'])}).refine(v=>v.old>=v.price,{message:'Compare-at price cannot be below the selling price.'}).refine(v=>!v.offerPrice||v.offerPrice<v.price,{message:'Offer price must be lower than the sale price.'}).refine(v=>!(v.offerStart&&v.offerEnd)||v.offerStart<=v.offerEnd,{message:'Offer end date cannot be before the start date.'}).parse(d);
 const row=await sql('SELECT * FROM listing_drafts WHERE id=?',input.id).first<any>();if(!row)throw new AccessError(404,'Draft not found.');const data=information.parse(JSON.parse(row.data));const ids=data.variants.map((v,i)=>'listing-'+input.id+'-'+i);if(row.state==='complete')return reply({ok:true,ids});
 const guard=crypto.randomUUID(),statements=[...actorGuard(u),sql("INSERT INTO access_guard (id,ok) SELECT ?,CASE WHEN EXISTS(SELECT 1 FROM listing_drafts WHERE id=? AND state='draft') THEN 1 ELSE 0 END",guard,input.id),sql('DELETE FROM access_guard WHERE id=?',guard)];
 data.variants.forEach((v,i)=>{const name=input.name+(v.color==='Not applicable'?'':' · '+v.color)+(v.option==='Standard'?'':' · '+v.option);const product={id:ids[i],name,category:data.category,subcategory:data.subcategory,sku:data.sku+'-'+String(i+1).padStart(2,'0'),listingGroup:input.id,...v,price:input.price,old:input.old,offerPrice:input.offerPrice||0,offerStart:input.offerStart||'',offerEnd:input.offerEnd||'',pricingType:'offer',status:input.status,tag:'New arrival',description:input.description,features:input.features};statements.push(sql('INSERT INTO catalog_records (id,data,status) VALUES (?,?,?)',product.id,JSON.stringify(product),input.status));});
 statements.push(sql("UPDATE listing_drafts SET state='complete' WHERE id=?",input.id),await audit(u,'content.listing_created',input.id,'Created product listings',{ids,status:input.status}));await database().batch(statements);return reply({ok:true,ids},201);
 }catch(e){if(e instanceof z.ZodError){const errors=validationMessages(e);return reply({error:errors[0]||'Check the product information.',errors},400)}return fail(e)}}
